import Head from "next/head";
//import Image from 'next/image';
import styles from "../styles/Home.module.css";
//import logo from '../public/favicon.ico';
import HomeContent from "../components/HomeContent";

export default function Home() {
  return (
    <>
        <Head>
          <title>Narrative Trails | Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <HomeContent />
    </>
  );
}
