import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import logo from '../public/logo.png';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Narrative Trails | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
        {/* <img src={logo} alt="logo" /> */}
        <h1 className={styles.title}>Homepage</h1>
        <p className={styles.text}>This is a sample text</p>
        <a className={styles.btn} href="https://narrativetrails.xyz/" target="_blank" rel="noopener noreferrer">About</a>
    </div>
  )
}
